-- MySQL Script generated by MySQL Workbench
-- Fri Aug 24 15:53:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_cc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cc` DEFAULT CHARACTER SET utf8 ;
USE `db_cc` ;

-- -----------------------------------------------------
-- Table `db_cc`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(70) NOT NULL,
  `login_usuario` VARCHAR(15) NOT NULL,
  `senha_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_crianca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_crianca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeCrianca` VARCHAR(60) NOT NULL,
  `partoCrianca` VARCHAR(10) NOT NULL,
  `horaNascCrianca` VARCHAR(5) NULL,
  `dataNascCrianca` VARCHAR(10) NOT NULL,
  `pesoCrianca` DOUBLE NOT NULL,
  `alturaCrianca` DOUBLE NULL,
  `sexoCrianca` CHAR(1) NULL,
  `endereco` VARCHAR(100) NULL,
  `localidade` VARCHAR(50) NULL,
  `idPai` INT NOT NULL,
  `idMae` INT NOT NULL,
  `idadeGestacional` INT NOT NULL,
  `key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_vacinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_vacinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apl1` VARCHAR(10) NULL,
  `apl2` VARCHAR(10) NULL,
  `apl3` VARCHAR(10) NULL,
  `ref1` VARCHAR(10) NULL,
  `ref2` VARCHAR(10) NULL,
  `tipo` VARCHAR(16) NOT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_testes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_testes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tPData` VARCHAR(10) NULL,
  `tPResul` VARCHAR(15) NULL,
  `tOrellhaData` VARCHAR(10) NULL,
  `tOrelhaResul` VARCHAR(15) NULL,
  `tLinguaData` VARCHAR(10) NULL,
  `tLinguaResul` VARCHAR(15) NULL,
  `perCefalicoCrianca` DOUBLE NULL,
  `perToraxico` DOUBLE NULL,
  `apgar1Crianca` INT NULL,
  `apgar5Crianca` INT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_pai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_pai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_pai` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  `membrosFamilia` INT NOT NULL,
  `renda` DOUBLE NULL,
  `profissao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_mae` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_mae` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  `profissao` VARCHAR(60) NOT NULL,
  `numConPN` INT NOT NULL,
  `filhosV` INT NOT NULL,
  `filhosM` INT NOT NULL,
  `filhosA` INT NOT NULL,
  `municipioPN` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_peso_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_peso_semana` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semana` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
