-- MySQL Script generated by MySQL Workbench
-- Fri Aug 24 07:17:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_cc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cc` DEFAULT CHARACTER SET utf8 ;
USE `db_cc` ;

-- -----------------------------------------------------
-- Table `db_cc`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(70) NOT NULL,
  `login_usuario` VARCHAR(15) NOT NULL,
  `senha_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_pai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_pai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_pai` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  `membrosFamilia` INT NOT NULL,
  `renda` DOUBLE NULL,
  `profissao` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_mae` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_mae` VARCHAR(60) NOT NULL,
  `idade` INT NOT NULL,
  `profissao` VARCHAR(60) NOT NULL,
  `numConPN` INT NOT NULL,
  `filhosV` INT NOT NULL,
  `filhosM` INT NOT NULL,
  `filhosA` INT NOT NULL,
  `municipioPN` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_crianca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_crianca` (
  `id` INT NOT NULL,
  `nomeCrianca` VARCHAR(60) NOT NULL,
  `partoCrianca` VARCHAR(10) NOT NULL,
  `horaNascCrianca` VARCHAR(5) NULL,
  `dataNascCrianca` DATE NOT NULL,
  `pesoCrianca` DOUBLE NULL,
  `alturaCrianca` DOUBLE NULL,
  `sexoCrianca` CHAR(1) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `localidade` VARCHAR(50) NULL,
  `idPai` INT NOT NULL,
  `idMae` INT NOT NULL,
  `idadeGestacional` INT NOT NULL,
  `key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `idPai`, `idMae`),
  INDEX `fk_tb_crianca_tb_pai1_idx` (`idPai` ASC),
  INDEX `fk_tb_crianca_tb_mae1_idx` (`idMae` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  CONSTRAINT `fk_tb_crianca_tb_pai1`
    FOREIGN KEY (`idPai`)
    REFERENCES `db_cc`.`tb_pai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_crianca_tb_mae1`
    FOREIGN KEY (`idMae`)
    REFERENCES `db_cc`.`tb_mae` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_vacinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_vacinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apl1` DATE NULL,
  `apl2` DATE NULL,
  `apl3` DATE NULL,
  `ref1` DATE NULL,
  `ref2` DATE NULL,
  `tipo` VARCHAR(16) NOT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`, `idCrianca`),
  INDEX `fk_tb_vacinas_tb_crianca1_idx` (`idCrianca` ASC),
  CONSTRAINT `fk_tb_vacinas_tb_crianca1`
    FOREIGN KEY (`idCrianca`)
    REFERENCES `db_cc`.`tb_crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_testes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_testes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tPData` DATE NULL,
  `tPResul` VARCHAR(15) NULL,
  `tOrellhaData` DATE NULL,
  `tOrelhaResul` VARCHAR(15) NULL,
  `tLinguaData` DATE NULL,
  `tLinguaResul` VARCHAR(15) NULL,
  `perCefalicoCrianca` DOUBLE NULL,
  `perToraxico` DOUBLE NULL,
  `apgar1Crianca` INT NULL,
  `apgar5Crianca` INT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`, `idCrianca`),
  INDEX `fk_tb_testes_tb_crianca1_idx` (`idCrianca` ASC),
  CONSTRAINT `fk_tb_testes_tb_crianca1`
    FOREIGN KEY (`idCrianca`)
    REFERENCES `db_cc`.`tb_crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cc`.`tb_peso_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cc`.`tb_peso_semana` (
  `id` INT NOT NULL,
  `semana` INT NOT NULL,
  `data` DATE NOT NULL,
  `peso` DOUBLE NOT NULL,
  `idCrianca` INT NOT NULL,
  PRIMARY KEY (`id`, `idCrianca`),
  INDEX `fk_tb_peso_semana_tb_crianca1_idx` (`idCrianca` ASC),
  CONSTRAINT `fk_tb_peso_semana_tb_crianca1`
    FOREIGN KEY (`idCrianca`)
    REFERENCES `db_cc`.`tb_crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
